/*
 Navicat Premium Data Transfer

 Source Server         : Oracle
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : 127.0.0.1:1521
 Source Schema         : XUYEWEI

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 25/12/2019 20:40:57
*/


-- ----------------------------
-- Table structure for MEMBER
-- ----------------------------
DROP TABLE "XUYEWEI"."MEMBER";
CREATE TABLE "XUYEWEI"."MEMBER" (
  "ID" VARCHAR2(32 BYTE) DEFAULT SYS_GUID()  NOT NULL ,
  "NAME" VARCHAR2(20 BYTE) ,
  "NICKNAME" VARCHAR2(20 BYTE) ,
  "PHONENUM" VARCHAR2(20 BYTE) ,
  "EMAIL" VARCHAR2(20 BYTE) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for ORDERS
-- ----------------------------
DROP TABLE "XUYEWEI"."ORDERS";
CREATE TABLE "XUYEWEI"."ORDERS" (
  "ID" VARCHAR2(32 BYTE) DEFAULT SYS_GUID()  NOT NULL ,
  "ORDERNUM" VARCHAR2(20 BYTE) NOT NULL ,
  "ORDERTIME" TIMESTAMP(6) ,
  "PEOPLECOUNT" NUMBER ,
  "ORDERDESC" VARCHAR2(500 BYTE) ,
  "PAYTYPE" NUMBER ,
  "ORDERSTATUS" NUMBER ,
  "PRODUCTID" VARCHAR2(32 BYTE) ,
  "MEMBERID" VARCHAR2(32 BYTE) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for ORDER_TRAVELLER
-- ----------------------------
DROP TABLE "XUYEWEI"."ORDER_TRAVELLER";
CREATE TABLE "XUYEWEI"."ORDER_TRAVELLER" (
  "ORDERID" VARCHAR2(32 BYTE) NOT NULL ,
  "TRAVELLERID" VARCHAR2(32 BYTE) NOT NULL 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for PERMISSION
-- ----------------------------
DROP TABLE "XUYEWEI"."PERMISSION";
CREATE TABLE "XUYEWEI"."PERMISSION" (
  "ID" VARCHAR2(32 BYTE) DEFAULT SYS_GUID()  NOT NULL ,
  "PERMISSIONNAME" VARCHAR2(50 BYTE) ,
  "URL" VARCHAR2(50 BYTE) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for PRODUCT
-- ----------------------------
DROP TABLE "XUYEWEI"."PRODUCT";
CREATE TABLE "XUYEWEI"."PRODUCT" (
  "ID" VARCHAR2(32 BYTE) DEFAULT SYS_GUID()  NOT NULL ,
  "PRODUCTNUM" VARCHAR2(50 BYTE) NOT NULL ,
  "PRODUCTNAME" VARCHAR2(50 BYTE) ,
  "CITYNAME" VARCHAR2(50 BYTE) ,
  "DEPARTURETIME" TIMESTAMP(6) ,
  "PRODUCTPRICE" NUMBER ,
  "PRODUCTDESC" VARCHAR2(500 BYTE) ,
  "PRODUCTSTATUS" NUMBER 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for ROLE
-- ----------------------------
DROP TABLE "XUYEWEI"."ROLE";
CREATE TABLE "XUYEWEI"."ROLE" (
  "ID" VARCHAR2(32 BYTE) DEFAULT SYS_GUID()  NOT NULL ,
  "ROLENAME" VARCHAR2(50 BYTE) ,
  "ROLEDESC" VARCHAR2(50 BYTE) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for ROLE_PERMISSION
-- ----------------------------
DROP TABLE "XUYEWEI"."ROLE_PERMISSION";
CREATE TABLE "XUYEWEI"."ROLE_PERMISSION" (
  "PERMISSIONID" VARCHAR2(100 BYTE) NOT NULL ,
  "ROLEID" VARCHAR2(100 BYTE) NOT NULL 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for SYSLOG
-- ----------------------------
DROP TABLE "XUYEWEI"."SYSLOG";
CREATE TABLE "XUYEWEI"."SYSLOG" (
  "ID" VARCHAR2(32 BYTE) DEFAULT SYS_GUID()  NOT NULL ,
  "VISITTIME" TIMESTAMP(6) ,
  "USERNAME" VARCHAR2(50 BYTE) ,
  "IP" VARCHAR2(30 BYTE) ,
  "URL" VARCHAR2(50 BYTE) ,
  "EXECUTIONTIME" NUMBER ,
  "METHOD" VARCHAR2(200 BYTE) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for TRAVELLER
-- ----------------------------
DROP TABLE "XUYEWEI"."TRAVELLER";
CREATE TABLE "XUYEWEI"."TRAVELLER" (
  "ID" VARCHAR2(32 BYTE) DEFAULT SYS_GUID()  NOT NULL ,
  "NAME" VARCHAR2(20 BYTE) ,
  "SEX" VARCHAR2(20 BYTE) ,
  "PHONENUM" VARCHAR2(20 BYTE) ,
  "CREDENTIALSTYPE" NUMBER ,
  "CREDENTIALSNUM" VARCHAR2(50 BYTE) ,
  "TRAVELLERTYPE" NUMBER 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for USERS
-- ----------------------------
DROP TABLE "XUYEWEI"."USERS";
CREATE TABLE "XUYEWEI"."USERS" (
  "ID" VARCHAR2(32 BYTE) DEFAULT SYS_GUID()  NOT NULL ,
  "EMAIL" VARCHAR2(50 BYTE) NOT NULL ,
  "USERNAME" VARCHAR2(50 BYTE) ,
  "PASSWORD" VARCHAR2(60 BYTE) ,
  "PHONENUM" VARCHAR2(20 BYTE) ,
  "STATUS" NUMBER 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for USERS_ROLE
-- ----------------------------
DROP TABLE "XUYEWEI"."USERS_ROLE";
CREATE TABLE "XUYEWEI"."USERS_ROLE" (
  "USERID" VARCHAR2(32 BYTE) NOT NULL ,
  "ROLEID" VARCHAR2(32 BYTE) NOT NULL 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Primary Key structure for table MEMBER
-- ----------------------------
ALTER TABLE "XUYEWEI"."MEMBER" ADD CONSTRAINT "SYS_C0018308" PRIMARY KEY ("ID");

-- ----------------------------
-- Primary Key structure for table ORDERS
-- ----------------------------
ALTER TABLE "XUYEWEI"."ORDERS" ADD CONSTRAINT "SYS_C0018310" PRIMARY KEY ("ID");

-- ----------------------------
-- Uniques structure for table ORDERS
-- ----------------------------
ALTER TABLE "XUYEWEI"."ORDERS" ADD CONSTRAINT "SYS_C0018311" UNIQUE ("ORDERNUM") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table ORDERS
-- ----------------------------
ALTER TABLE "XUYEWEI"."ORDERS" ADD CONSTRAINT "SYS_C0018309" CHECK ("ORDERNUM" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table ORDER_TRAVELLER
-- ----------------------------
ALTER TABLE "XUYEWEI"."ORDER_TRAVELLER" ADD CONSTRAINT "SYS_C0018314" PRIMARY KEY ("ORDERID", "TRAVELLERID");

-- ----------------------------
-- Primary Key structure for table PERMISSION
-- ----------------------------
ALTER TABLE "XUYEWEI"."PERMISSION" ADD CONSTRAINT "SYS_C0018343" PRIMARY KEY ("ID");

-- ----------------------------
-- Primary Key structure for table PRODUCT
-- ----------------------------
ALTER TABLE "XUYEWEI"."PRODUCT" ADD CONSTRAINT "SYS_C0018227" PRIMARY KEY ("ID");

-- ----------------------------
-- Uniques structure for table PRODUCT
-- ----------------------------
ALTER TABLE "XUYEWEI"."PRODUCT" ADD CONSTRAINT "PRODUCT" UNIQUE ("ID", "PRODUCTNUM") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table PRODUCT
-- ----------------------------
ALTER TABLE "XUYEWEI"."PRODUCT" ADD CONSTRAINT "SYS_C0018226" CHECK ("PRODUCTNUM" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table ROLE
-- ----------------------------
ALTER TABLE "XUYEWEI"."ROLE" ADD CONSTRAINT "SYS_C0018339" PRIMARY KEY ("ID");

-- ----------------------------
-- Primary Key structure for table ROLE_PERMISSION
-- ----------------------------
ALTER TABLE "XUYEWEI"."ROLE_PERMISSION" ADD CONSTRAINT "SYS_C0018344" PRIMARY KEY ("PERMISSIONID", "ROLEID");

-- ----------------------------
-- Primary Key structure for table SYSLOG
-- ----------------------------
ALTER TABLE "XUYEWEI"."SYSLOG" ADD CONSTRAINT "SYS_C0018398" PRIMARY KEY ("ID");

-- ----------------------------
-- Primary Key structure for table TRAVELLER
-- ----------------------------
ALTER TABLE "XUYEWEI"."TRAVELLER" ADD CONSTRAINT "SYS_C0018307" PRIMARY KEY ("ID");

-- ----------------------------
-- Primary Key structure for table USERS
-- ----------------------------
ALTER TABLE "XUYEWEI"."USERS" ADD CONSTRAINT "SYS_C0018337" PRIMARY KEY ("ID");

-- ----------------------------
-- Uniques structure for table USERS
-- ----------------------------
ALTER TABLE "XUYEWEI"."USERS" ADD CONSTRAINT "SYS_C0018338" UNIQUE ("EMAIL") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table USERS
-- ----------------------------
ALTER TABLE "XUYEWEI"."USERS" ADD CONSTRAINT "SYS_C0018336" CHECK ("EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table USERS_ROLE
-- ----------------------------
ALTER TABLE "XUYEWEI"."USERS_ROLE" ADD CONSTRAINT "SYS_C0018340" PRIMARY KEY ("USERID", "ROLEID");

-- ----------------------------
-- Foreign Keys structure for table ORDERS
-- ----------------------------
ALTER TABLE "XUYEWEI"."ORDERS" ADD CONSTRAINT "SYS_C0018312" FOREIGN KEY ("PRODUCTID") REFERENCES "PRODUCT" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XUYEWEI"."ORDERS" ADD CONSTRAINT "SYS_C0018313" FOREIGN KEY ("MEMBERID") REFERENCES "MEMBER" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table ORDER_TRAVELLER
-- ----------------------------
ALTER TABLE "XUYEWEI"."ORDER_TRAVELLER" ADD CONSTRAINT "SYS_C0018315" FOREIGN KEY ("ORDERID") REFERENCES "ORDERS" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XUYEWEI"."ORDER_TRAVELLER" ADD CONSTRAINT "SYS_C0018316" FOREIGN KEY ("TRAVELLERID") REFERENCES "TRAVELLER" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table ROLE_PERMISSION
-- ----------------------------
ALTER TABLE "XUYEWEI"."ROLE_PERMISSION" ADD CONSTRAINT "SYS_C0018345" FOREIGN KEY ("PERMISSIONID") REFERENCES "PERMISSION" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XUYEWEI"."ROLE_PERMISSION" ADD CONSTRAINT "SYS_C0018346" FOREIGN KEY ("ROLEID") REFERENCES "ROLE" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table USERS_ROLE
-- ----------------------------
ALTER TABLE "XUYEWEI"."USERS_ROLE" ADD CONSTRAINT "SYS_C0018341" FOREIGN KEY ("USERID") REFERENCES "USERS" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XUYEWEI"."USERS_ROLE" ADD CONSTRAINT "SYS_C0018342" FOREIGN KEY ("ROLEID") REFERENCES "ROLE" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
